<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hrh</groupId>
    <artifactId>dagproject</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <description>
        dag json 调度的项目：
            服务编排（http调度）；
            dag调度（http、py、sql、spark、shell、yarn插件化调度算子包）；
            算子包插件；
    </description>
    <modules>
        <module>servicearrange</module>
    </modules>

    <properties>
        <!-- 依赖版本号管理 -->
        <spring-boot.version>2.1.5.RELEASE</spring-boot.version>
        <data-mongodb.version>2.1.8.RELEASE</data-mongodb.version>
        <curator.version>4.0.1</curator.version>
        <lombok.version>1.18.8</lombok.version>
        <rabbit.version>2.1.4.RELEASE</rabbit.version>
        <hutool.version>5.7.17</hutool.version>
        <base.version>1.0-SNAPSHOT</base.version>
        <eureka.version>2.1.3.RELEASE</eureka.version>
        <apollo.version>1.8.0</apollo.version>
        <servletapi.version>4.0.1</servletapi.version>
    </properties>



</project>