apollo:
  bootstrap:
    eagerLoad:
      #true：Apollo的加载顺序放到日志系统加载之前，不过这会导致Apollo的启动过程无法通过日志的方式输出(因为执行Apollo加载的时候，
      #日志系统压根没有准备好呢！所以在Apollo代码中使用Slf4j的日志输出便没有任何内容)
      enabled: false
    namespaces: application.common #Apollo命名空间

eureka:
  client:
    service-url:
      defaultZone: ${eureka-url} #eureka 默认地址
  instance:
    #注册名
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port:8080}}
    #将IP注册到Eureka Server上，而如果不配置就是机器的主机名
    ip-address: 8.129.116.16
    prefer-ip-address: true
    #状态页面的URL，相对路径，默认使用 HTTP 访问，如需使用 HTTPS则要使用绝对路径配置，缺省：/test/public/info
    status-page-url-path: /test/public/info

server:
  port: 8082 #服务器端口
  servlet:
    context-path: /servicearrange #应用的上下文路径

spring:
  application:
    name: servicearrange #项目名称
  #rabbitmq配置
  cloud:
    stream:
      binders:
        rabbit_cluster:
          environment:
            spring:
              rabbitmq:
                addresses: 8.129.116.16:5672
                password: guest
                username: guest
          type: rabbit
      bindings:
        output_channel:
          binder: rabbit_cluster
          content-type: application/json
          destination: ${spring.application.name}-exchange-point
        shell_task_status_channel:
          binder: rabbit_cluster
          content-type: application/json
          destination: ${spring.application.name}-exchange-point
          group: ${task.shell_task_status}
        task_result_input_channel:
          binder: rabbit_cluster
          consumer:
            concurrency: 1
          content-type: application/json
          destination: ${spring.application.name}-exchange-point
          group: ${task.result_queue_name}
        task_run_input_channel:
          binder: rabbit_cluster
          consumer:
            concurrency: 1
          content-type: application/json
          destination: ${spring.application.name}-exchange-point
          group: ${task.run_queue_name}
      rabbit:
        bindings:
          output_channel:
            producer:
              routing-key-expression: headers.receiveSign
          shell_task_status_channel:
            consumer:
              binding-routing-key: ${{task.shell_task_status}
          task_result_input_channel:
            consumer:
              acknowledge-mode: manual
              binding-routing-key: ${task.result_queue_name}
          task_run_input_channel:
            consumer:
              acknowledge-mode: manual
              binding-routing-key: ${task.run_queue_name}
  #mongodb配置
  data:
    mongodb:
      database: admin
      host: 8.129.116.16
      password: 123456
      port: 27017
      username: admin
  #指定打包环境
  profiles:
    active: jar

#zk配置
zk:
  session-timeout: 5000
  url: 8.129.116.16:2181

task:
  result_queue_name: /task/result
  run_queue_name: /task/run