#服务器端口
server.port=8082
#应用的上下文路径
server.servlet.context-path=/servicearrange
#打包环境
#使用默认打包环境:jar
#spring.profiles.active=${pom.package}
#指定打包环境
spring.profiles.active=jar
#项目名称
spring.application.name=servicearrange
#eureka 默认地址
eureka.client.service-url.defaultZone=${eureka-url}
#将IP注册到Eureka Server上，而如果不配置就是机器的主机名
eureka.instance.ip-address=8.129.116.16
eureka.instance.prefer-ip-address=true
#注册名默认是“IP名:应用名:应用端口名”
#eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port:8080}}
eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port:8080}}
#状态页面的URL，相对路径，默认使用 HTTP 访问，如需使用 HTTPS则要使用绝对路径配置，缺省：/test/public/info
eureka.instance.status-page-url-path=/test/public/info
#Apollo命名空间
apollo.bootstrap.namespaces=application,rscenter.common
#true：Apollo的加载顺序放到日志系统加载之前，不过这会导致Apollo的启动过程无法通过日志的方式输出(因为执行Apollo加载的时候，日志系统压根没有准备好呢！所以在Apollo代码中使用Slf4j的日志输出便没有任何内容)
apollo.bootstrap.eagerLoad.enabled=false
#mongodb配置
spring.data.mongodb.enabled=true
spring.data.mongodb.host=8.129.116.16
spring.data.mongodb.port=27017
spring.data.mongodb.database=admin
spring.data.mongodb.username=admin
spring.data.mongodb.password=123456
spring.data.mongodb.min-connections-per-host=10
spring.data.mongodb.max-connections-per-host=100
spring.data.mongodb.threads-allowed-to-block-for-connection-multiplier=5
spring.data.mongodb.server-selection-timeout=30000
spring.data.mongodb.max-wait-time=120000
spring.data.mongodb.max-connection-idel-time=0
spring.data.mongodb.max-connection-life-time=0
spring.data.mongodb.connect-timeout=10000
spring.data.mongodb.socket-timeout=0
spring.data.mongodb.socket-keep-alive=false
spring.data.mongodb.ssl-enabled=false
spring.data.mongodb.ssl-invalid-host-name-allowed=false
spring.data.mongodb.always-use-m-beans=false
spring.data.mongodb.heartbeat-socket-timeout=20000
spring.data.mongodb.heartbeat-connect-timeout=20000
spring.data.mongodb.min-heartbeat-frequency=500
spring.data.mongodb.heartbeat-frequency=10000
spring.data.mongodb.local-threshold=15

